/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentSignupRouteImport } from './routes/student-signup'
import { Route as StudentLoginRouteImport } from './routes/student-login'
import { Route as StudentRouteImport } from './routes/student'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LecturerLoginRouteImport } from './routes/lecturer-login'
import { Route as LecturerRouteImport } from './routes/lecturer'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as LecturerIndexRouteImport } from './routes/lecturer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentMyCoursesRouteImport } from './routes/student.my-courses'
import { Route as StudentHistoryRouteImport } from './routes/student.history'
import { Route as StudentAvailableCoursesRouteImport } from './routes/student.available-courses'
import { Route as LecturerSessionsAttendanceRouteImport } from './routes/lecturer.sessions-attendance'
import { Route as LecturerRecordsRouteImport } from './routes/lecturer.records'
import { Route as LecturerCoursesRouteImport } from './routes/lecturer.courses'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminLecturersRouteImport } from './routes/admin.lecturers'

const StudentSignupRoute = StudentSignupRouteImport.update({
  id: '/student-signup',
  path: '/student-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student-login',
  path: '/student-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerLoginRoute = LecturerLoginRouteImport.update({
  id: '/lecturer-login',
  path: '/lecturer-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerRoute = LecturerRouteImport.update({
  id: '/lecturer',
  path: '/lecturer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const LecturerIndexRoute = LecturerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LecturerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentMyCoursesRoute = StudentMyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHistoryRoute = StudentHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAvailableCoursesRoute = StudentAvailableCoursesRouteImport.update({
  id: '/available-courses',
  path: '/available-courses',
  getParentRoute: () => StudentRoute,
} as any)
const LecturerSessionsAttendanceRoute =
  LecturerSessionsAttendanceRouteImport.update({
    id: '/sessions-attendance',
    path: '/sessions-attendance',
    getParentRoute: () => LecturerRoute,
  } as any)
const LecturerRecordsRoute = LecturerRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => LecturerRoute,
} as any)
const LecturerCoursesRoute = LecturerCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LecturerRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLecturersRoute = AdminLecturersRouteImport.update({
  id: '/lecturers',
  path: '/lecturers',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/change-password': typeof ChangePasswordRoute
  '/lecturer': typeof LecturerRouteWithChildren
  '/lecturer-login': typeof LecturerLoginRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/student-login': typeof StudentLoginRoute
  '/student-signup': typeof StudentSignupRoute
  '/admin/lecturers': typeof AdminLecturersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/lecturer/records': typeof LecturerRecordsRoute
  '/lecturer/sessions-attendance': typeof LecturerSessionsAttendanceRoute
  '/student/available-courses': typeof StudentAvailableCoursesRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/my-courses': typeof StudentMyCoursesRoute
  '/admin/': typeof AdminIndexRoute
  '/lecturer/': typeof LecturerIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/change-password': typeof ChangePasswordRoute
  '/lecturer-login': typeof LecturerLoginRoute
  '/login': typeof LoginRoute
  '/student-login': typeof StudentLoginRoute
  '/student-signup': typeof StudentSignupRoute
  '/admin/lecturers': typeof AdminLecturersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/lecturer/records': typeof LecturerRecordsRoute
  '/lecturer/sessions-attendance': typeof LecturerSessionsAttendanceRoute
  '/student/available-courses': typeof StudentAvailableCoursesRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/my-courses': typeof StudentMyCoursesRoute
  '/admin': typeof AdminIndexRoute
  '/lecturer': typeof LecturerIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/change-password': typeof ChangePasswordRoute
  '/lecturer': typeof LecturerRouteWithChildren
  '/lecturer-login': typeof LecturerLoginRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/student-login': typeof StudentLoginRoute
  '/student-signup': typeof StudentSignupRoute
  '/admin/lecturers': typeof AdminLecturersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/lecturer/records': typeof LecturerRecordsRoute
  '/lecturer/sessions-attendance': typeof LecturerSessionsAttendanceRoute
  '/student/available-courses': typeof StudentAvailableCoursesRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/my-courses': typeof StudentMyCoursesRoute
  '/admin/': typeof AdminIndexRoute
  '/lecturer/': typeof LecturerIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/change-password'
    | '/lecturer'
    | '/lecturer-login'
    | '/login'
    | '/student'
    | '/student-login'
    | '/student-signup'
    | '/admin/lecturers'
    | '/admin/reports'
    | '/admin/students'
    | '/lecturer/courses'
    | '/lecturer/records'
    | '/lecturer/sessions-attendance'
    | '/student/available-courses'
    | '/student/history'
    | '/student/my-courses'
    | '/admin/'
    | '/lecturer/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/change-password'
    | '/lecturer-login'
    | '/login'
    | '/student-login'
    | '/student-signup'
    | '/admin/lecturers'
    | '/admin/reports'
    | '/admin/students'
    | '/lecturer/courses'
    | '/lecturer/records'
    | '/lecturer/sessions-attendance'
    | '/student/available-courses'
    | '/student/history'
    | '/student/my-courses'
    | '/admin'
    | '/lecturer'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/change-password'
    | '/lecturer'
    | '/lecturer-login'
    | '/login'
    | '/student'
    | '/student-login'
    | '/student-signup'
    | '/admin/lecturers'
    | '/admin/reports'
    | '/admin/students'
    | '/lecturer/courses'
    | '/lecturer/records'
    | '/lecturer/sessions-attendance'
    | '/student/available-courses'
    | '/student/history'
    | '/student/my-courses'
    | '/admin/'
    | '/lecturer/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LecturerRoute: typeof LecturerRouteWithChildren
  LecturerLoginRoute: typeof LecturerLoginRoute
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
  StudentLoginRoute: typeof StudentLoginRoute
  StudentSignupRoute: typeof StudentSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-signup': {
      id: '/student-signup'
      path: '/student-signup'
      fullPath: '/student-signup'
      preLoaderRoute: typeof StudentSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-login': {
      id: '/student-login'
      path: '/student-login'
      fullPath: '/student-login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer-login': {
      id: '/lecturer-login'
      path: '/lecturer-login'
      fullPath: '/lecturer-login'
      preLoaderRoute: typeof LecturerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer': {
      id: '/lecturer'
      path: '/lecturer'
      fullPath: '/lecturer'
      preLoaderRoute: typeof LecturerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/lecturer/': {
      id: '/lecturer/'
      path: '/'
      fullPath: '/lecturer/'
      preLoaderRoute: typeof LecturerIndexRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/my-courses': {
      id: '/student/my-courses'
      path: '/my-courses'
      fullPath: '/student/my-courses'
      preLoaderRoute: typeof StudentMyCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/history': {
      id: '/student/history'
      path: '/history'
      fullPath: '/student/history'
      preLoaderRoute: typeof StudentHistoryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/available-courses': {
      id: '/student/available-courses'
      path: '/available-courses'
      fullPath: '/student/available-courses'
      preLoaderRoute: typeof StudentAvailableCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/lecturer/sessions-attendance': {
      id: '/lecturer/sessions-attendance'
      path: '/sessions-attendance'
      fullPath: '/lecturer/sessions-attendance'
      preLoaderRoute: typeof LecturerSessionsAttendanceRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/records': {
      id: '/lecturer/records'
      path: '/records'
      fullPath: '/lecturer/records'
      preLoaderRoute: typeof LecturerRecordsRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/courses': {
      id: '/lecturer/courses'
      path: '/courses'
      fullPath: '/lecturer/courses'
      preLoaderRoute: typeof LecturerCoursesRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lecturers': {
      id: '/admin/lecturers'
      path: '/lecturers'
      fullPath: '/admin/lecturers'
      preLoaderRoute: typeof AdminLecturersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLecturersRoute: typeof AdminLecturersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLecturersRoute: AdminLecturersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LecturerRouteChildren {
  LecturerCoursesRoute: typeof LecturerCoursesRoute
  LecturerRecordsRoute: typeof LecturerRecordsRoute
  LecturerSessionsAttendanceRoute: typeof LecturerSessionsAttendanceRoute
  LecturerIndexRoute: typeof LecturerIndexRoute
}

const LecturerRouteChildren: LecturerRouteChildren = {
  LecturerCoursesRoute: LecturerCoursesRoute,
  LecturerRecordsRoute: LecturerRecordsRoute,
  LecturerSessionsAttendanceRoute: LecturerSessionsAttendanceRoute,
  LecturerIndexRoute: LecturerIndexRoute,
}

const LecturerRouteWithChildren = LecturerRoute._addFileChildren(
  LecturerRouteChildren,
)

interface StudentRouteChildren {
  StudentAvailableCoursesRoute: typeof StudentAvailableCoursesRoute
  StudentHistoryRoute: typeof StudentHistoryRoute
  StudentMyCoursesRoute: typeof StudentMyCoursesRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAvailableCoursesRoute: StudentAvailableCoursesRoute,
  StudentHistoryRoute: StudentHistoryRoute,
  StudentMyCoursesRoute: StudentMyCoursesRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LecturerRoute: LecturerRouteWithChildren,
  LecturerLoginRoute: LecturerLoginRoute,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
  StudentLoginRoute: StudentLoginRoute,
  StudentSignupRoute: StudentSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
